apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: loki-operator
  template:
    metadata:
      labels:
        name: loki-operator
    spec:
      serviceAccountName: loki-operator
      containers:
        - name: loki-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - loki-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "loki-operator"
